In [2]:
# 단어 수준의 One-Hot-Encoding

import numpy as np

samples = ['The cat sat on the mat.', 'The dog ate my homework']

token_index = {} # 데이터에 있는 모든 토큰의 인덱스 구축

for sample in samples:
    for word in sample.split():
        if word not in token_index:
            token_index[word] = len(token_index) + 1 # 단어마다 고유한 인덱스 할당 (0은 토큰 혹은 시퀀스패딩을 위해사용하지 않는다
max_length = 10 # 샘플을 벡터로 변환. 각 샘플에서 max_length까지 단어만 사용

results = np.zeros(shape=(len(samples), max_length, max(token_index.values()) + 1)) # 결과를 저장할 배열

print(results.shape)
print(token_index[word])

for i, sample in enumerate(samples):
    for j, word in list(enumerate(sample.split()))[:max_length]:
        index = token_index.get(word)
        results[i, j, index] = 1.
        
print(results)

(2, 10, 11)
10
[[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [6]:
# 문자 수준의 One-Hot-Encoding
import string

samples = ['The cat sat on the mat.', 'The dog ate my homework']
characters = string.printable # 출력 가능한 모든 ASCII 문자
print(characters)
token_index = dict(zip(characters, range(1, len(characters) + 1)))
print(len(token_index))

max_length = 50

results = np.zeros((len(samples), max_length, max(token_index.values()) + 1))
print(results.shape)
for i, sample in enumerate(samples):
    for j, character in enumerate(sample):
        index = token_index.get(character)
        results[i, j, index] = 1.
        
print(results)
    # Tokenizer(num_words = 1000)처럼 지정하면 인덱스 0을 제외하고 최대 999개까지 단어를 사용.
    # num_words 매개변수를 지정하지 않으면 고유한 단어의 전체 개수 + 1(인덱스 0)가 원-핫-인코딩의 길이

0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~ 	

100
(2, 50, 101)
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [9]:
# 케라스를 사용한 단어 수준의 One-Hot-Encoding
import tensorflow as tf
from tensorflow import keras
from keras.preprocessing.text import Tokenizer

samples = ['The cat sat on the mat', 'The dog ate my homework']

tokenizer = Tokenizer(num_words = 1000)
tokenizer.fit_on_texts(samples) # 단어 인덱스 구축

sequences = tokenizer.texts_to_sequences(samples) # 문자열을 정수 인덱스로 변환

one_hot_results = tokenizer.texts_to_matrix(samples, mode = 'binary')
    #mode 매개변수에서 지원하는 값 'count'출현횟수, 'freq'출현횟수를 전체 시퀀스 길이로 나누어 정규화, 'tfidf'TF-IDF방식
word_index = tokenizer.word_index # 계산된 단어 인덱스 구함
print('%s개의 고유한 토큰' %len(word_index))

9개의 고유한 토큰


In [15]:
# 해싱 기법을 사용하여 단어 수준의 One-Hot-Encoding
# 원-핫-인코딩의 변종 중 하나는 원-핫-해싱 기법이다. 이 방식은 어휘 사전에 있는 고유한 토큰의 수가 너무 커서 모두 다루기 어려울 때 사용한다.
# 각 단어에 명시적으로 인덱스를 할당하고 이 인덱스를 딕셔너리에 저장하는 대신 단어를 해싱하여 고정된 크기의 벡터로 변환.
# 명시적인 단어 인덱스가 필요 없으므로 메모리를 절약하고 온라인 방식으로 데이터 인코딩 가능(전체 데이터 확인 안하고 토큰 생성 가능)

# 해시 충돌(Hash Collision): 2개의 단어가 같은 해시를 만들면 모델은 단어 사이의 차이를 인식하지 못한다.
# 해싱 공간의 차원이 해싱될 고유-토큰의 전체 개수보다 훨씬 크면 해시 충돌의 가능성이 감소.

samples = ['The cat sat on the mat', 'The dog ate my homework']

dimensionality = 1000
max_length = 10

results = np.zeros((len(samples), max_length, dimensionality))
for i, sample in enumerate(samples):
    for j, word in list (enumerate(sample.split()))[:max_length]:
        index = abs(hash(word)) % dimensionality
        results[i, j, index] = 1.
print(results.shape, results, sep='\n')

(2, 10, 1000)
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
